(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("Lake",
{ "compressionlevel":-1,
 "height":50,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":6,
         "name":"Background",
         "objects":[
                {
                 "gid":5,
                 "height":1828,
                 "id":7,
                 "name":"sky",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":3616,
                 "x":-132,
                 "y":1666
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"Midground",
         "objects":[
                {
                 "gid":3,
                 "height":1772,
                 "id":8,
                 "name":"trees",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":3224,
                 "x":18,
                 "y":1654
                }, 
                {
                 "gid":4,
                 "height":1776,
                 "id":9,
                 "name":"waterfall",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":3260,
                 "x":6,
                 "y":1638
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Foreground",
         "objects":[
                {
                 "gid":1,
                 "height":1080,
                 "id":10,
                 "name":"clouds_large",
                 "properties":[
                        {
                         "name":"HorizontalSpeed",
                         "type":"float",
                         "value":0.5
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1920,
                 "x":300,
                 "y":1256
                }, 
                {
                 "gid":2,
                 "height":1080,
                 "id":11,
                 "name":"clouds_small",
                 "properties":[
                        {
                         "name":"HorizontalSpeed",
                         "type":"float",
                         "value":1
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1920,
                 "x":288,
                 "y":1260
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Colliders",
         "objects":[],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":7,
 "nextobjectid":12,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.4.2",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/..\/platformer-assets\/_images\/lake.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.4,
 "width":100
});